# Generated by Django 2.0 on 2017-12-03 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0002_auto_20171203_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 22, 20, 3, 830027, tzinfo=utc), verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 22, 20, 3, 844566, tzinfo=utc), verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 22, 20, 3, 845067, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
