# Generated by Django 2.0 on 2017-12-03 22:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0004_auto_20171203_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Service category name')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published')),
            ],
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(max_length=200, verbose_name='Product category name'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='isfrost_app.ServiceCategory'),
        ),
    ]
