# Generated by Django 2.0 on 2017-12-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0005_auto_20171203_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name='Product price'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_text',
            field=models.TextField(default='Engar nánari upplýsingar', verbose_name='About product'),
        ),
    ]
