# Generated by Django 2.0 on 2017-12-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0006_auto_20171204_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_text',
            field=models.TextField(default='Engar nánari upplýsingar', verbose_name='About service'),
        ),
    ]
