# Generated by Django 2.0 on 2017-12-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0009_auto_20171215_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(null=True, upload_to='images/products/%Y/%m'),
        ),
    ]
