# Generated by Django 2.0 on 2017-12-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0010_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category_image',
        ),
    ]
