# Generated by Django 2.0 on 2017-12-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0012_auto_20171215_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(null=True, upload_to='images/product_categories/%Y/%m'),
        ),
    ]
