# Generated by Django 2.0 on 2017-12-16 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0013_auto_20171216_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_description',
            field=models.TextField(default='Engar nánari upplýsingar', verbose_name='Um vöruflokk'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(max_length=200, verbose_name='Nafn vöruflokks'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Búið til þann'),
        ),
    ]
