# Generated by Django 2.0 on 2017-12-16 19:41

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0014_auto_20171216_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='category_icon',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='tákn'),
        ),
    ]
