# Generated by Django 2.0 on 2017-12-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0015_servicecategory_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='category_description',
            field=models.TextField(default='Engar nánari upplýsingar', verbose_name='Um vöruflokk'),
        ),
    ]
