# Generated by Django 2.0 on 2017-12-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0016_servicecategory_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='category_icon',
            field=models.CharField(max_length=20, null=True, verbose_name='tákn'),
        ),
    ]
