# Generated by Django 2.0 on 2017-12-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0017_auto_20171217_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='category_icon',
            field=models.CharField(help_text='1. Finna tákn hér: http://fontawesome.io/icons/ 2. Láta inn nafn, t.d. "address-book"', max_length=20, null=True, verbose_name='tákn'),
        ),
    ]
