# Generated by Django 2.0 on 2017-12-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0019_auto_20171218_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='images/products/%Y/%m'),
        ),
    ]
