# Generated by Django 2.0 on 2017-12-18 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0020_auto_20171218_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titill')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Undirtexti')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Búið til þann')),
                ('image', models.ImageField(null=True, upload_to='images/articles/%Y/%m')),
                ('text', models.TextField(verbose_name='Texti')),
            ],
            options={
                'verbose_name': 'Frétt',
                'verbose_name_plural': 'Fréttir',
            },
        ),
    ]
