# Generated by Django 2.0 on 2017-12-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0021_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='Gata')),
                ('postal_code', models.CharField(max_length=3, verbose_name='Póstnúmer')),
                ('city', models.CharField(max_length=200, verbose_name='Staður')),
                ('phone_number', models.CharField(max_length=7, verbose_name='símanúmer')),
                ('email', models.EmailField(max_length=254, verbose_name='póstur')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Frétt', 'verbose_name_plural': 'Fréttir'},
        ),
    ]
