# Generated by Django 2.0 on 2017-12-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0022_auto_20171218_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Fyrirtæki', 'verbose_name_plural': 'Fyrirtækið'},
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='Ísfrost', max_length=200, verbose_name='nafn'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=8, verbose_name='símanúmer'),
        ),
    ]
