# Generated by Django 2.0 on 2017-12-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0024_auto_20171218_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(null=True, verbose_name='Lýsing á forsíðu')),
                ('cover_image', models.ImageField(null=True, upload_to='images/company/%Y/%m', verbose_name='Forsíðumynd')),
            ],
            options={
                'verbose_name': 'Forsíða',
                'verbose_name_plural': 'Forsíðan',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='cover_image',
        ),
    ]
