# Generated by Django 2.0 on 2017-12-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0025_auto_20171218_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='detailed_description',
            field=models.TextField(default='Engar nánari upplýsingar', null=True, verbose_name='Nánar um vöruflokk'),
        ),
    ]
