# Generated by Django 2.0 on 2017-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0026_productcategory_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_text',
            field=models.TextField(default='Engar nánari upplýsingar', null=True, verbose_name='About product'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_description',
            field=models.TextField(default='Engar nánari upplýsingar', verbose_name='Stutt lýsing um vöruflokk'),
        ),
    ]
