# Generated by Django 2.0 on 2017-12-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0027_auto_20171222_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='category_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='category_description',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='detailed_description',
            field=models.TextField(default='Engar nánari upplýsingar', null=True, verbose_name='Nánar um þjónustuflokk'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='short_description',
            field=models.TextField(default='Engar nánari upplýsingar', verbose_name='Stutt lýsing um þjónustuflokk'),
        ),
    ]
