# Generated by Django 2.0 on 2017-12-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0028_auto_20171224_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(default='Engar nánari upplýsingar', null=True, verbose_name='Nánari upplýsingar um vöru'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='Engar nánari upplýsingar', verbose_name='Stutt lýsing um vöru'),
        ),
    ]
