# Generated by Django 2.0 on 2017-12-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0030_auto_20171224_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Vara', 'verbose_name_plural': 'Vörur'},
        ),
    ]
