# Generated by Django 2.0 on 2017-12-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0034_auto_20171227_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200, verbose_name='Póstur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Símanúmer'),
            preserve_default=False,
        ),
    ]
