# Generated by Django 2.0 on 2017-12-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0037_auto_20171227_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Verð'),
        ),
    ]
