# Generated by Django 2.0 on 2017-12-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0038_auto_20171227_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='about_description',
            field=models.TextField(blank=True, verbose_name='Lýsing fyrir fyrirtækjaupplýsingar'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='news_description',
            field=models.TextField(blank=True, verbose_name='Lýsing á fréttum'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='product_description',
            field=models.TextField(blank=True, verbose_name='Lýsing fyrir vörur'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='service_description',
            field=models.TextField(blank=True, verbose_name='Lýsing fyrir þjónustu'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='introduction',
            field=models.TextField(blank=True, default='', verbose_name='Lýsing á forsíðu'),
            preserve_default=False,
        ),
    ]
