# Generated by Django 2.0 on 2017-12-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0039_auto_20171228_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='text',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='Engar nánari upplýsingar', verbose_name='About service'),
        ),
    ]
