# Generated by Django 2.0 on 2017-12-28 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0040_auto_20171228_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='Engar nánari upplýsingar', verbose_name='Um þjónustu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Þjónusta'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Búið til þann'),
        ),
    ]
