# Generated by Django 2.0 on 2017-12-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0041_auto_20171228_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Texti á síðu um ísfrost')),
            ],
            options={
                'verbose_name': 'Um Ísfrost',
                'verbose_name_plural': 'Um Ísfrost',
            },
        ),
    ]
