# Generated by Django 2.0 on 2017-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0043_auto_20171229_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, default='images/defaults/user.png', null=True, upload_to='images/staff/%Y/%m'),
        ),
    ]
