# Generated by Django 2.0 on 2017-12-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0044_auto_20171229_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='images/defaults/article.png', null=True, upload_to='images/articles/%Y/%m'),
        ),
    ]
