# Generated by Django 2.0 on 2017-12-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0045_auto_20171229_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/defaults/product.png', null=True, upload_to='images/products/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, default='images/defaults/product.png', null=True, upload_to='images/product_categories/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, default='snowflake-o', help_text='1. Finna tákn hér: http://fontawesome.io/icons/ 2. Láta inn nafn, t.d. "address-book"', max_length=20, null=True, verbose_name='tákn'),
        ),
    ]
