# Generated by Django 2.0 on 2017-12-29 18:46

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0046_auto_20171229_1802'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension()
    ]
