# Generated by Django 2.0 on 2018-01-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isfrost_app', '0047_auto_20171229_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Póstur'),
        ),
    ]
